id: afec1a2afe21451baef6d136c9f09a3d
initial_creation_type: ocr
source_metadata:
  volumes:
    ceaf9673d2934758b1d93a7f5303f0cd:
      base_file: v066.txt
      image_group_id: I1PD95912
      title: བྱང་ཆུབ་ཀྱི་ལྟུང་བ་བཤགས་པའི་འགྲེལ་པ།
      total_pages: 1529
      volume_number: 67
